version: "3"
services:
  web:
    build: ./web/.
    command: npm start
    ports: 
      - "8080:3000"
    volumes:
      - "./web:/app"
    networks:
      - frontend
      - backend
  api:
    build: .
    command: npm start
    ports: 
      - "3000:3000"
    volumes: 
      - ".:/app"
    networks: 
      - backend
      - frontend
  mongodb:
    image: mongo
    restart: always
    env_file:
      - ./env/mongodb.env
    volumes: 
      - "./data/db:/data/db"
    ports:
      - "27017:27017"
    networks: 
      - backend
  mongo-express:
    image: mongo-express
    restart: always
    logging:
      driver: none
    env_file:
      - ./env/mongoexpress.env
    networks:
      - backend
      - frontend
    ports:
      - 8081:8081
    depends_on:
      - mongodb

networks:
  frontend:
  backend:

